# Generated by Django 4.2.3 on 2023-07-18 16:35

import api.utl
from django.conf import settings
import django.contrib.auth.models
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="cUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("mobile", models.CharField(max_length=26, unique=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("police", "Police"),
                            ("admin", "Admin"),
                        ],
                        default="user",
                        max_length=10,
                    ),
                ),
                ("address", models.TextField(null=True)),
                ("pincode", models.CharField(blank=True, max_length=10)),
                (
                    "otp_code",
                    models.CharField(blank=True, default=None, max_length=6, null=True),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Case",
            fields=[
                ("cid", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("drug", "Drug"),
                            ("vehicle", "Vehicle"),
                            ("extortion", "Extortion"),
                        ],
                        default="drug",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=250, null=True)),
                (
                    "cstate",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("assign", "Assign"),
                            ("transfer", "Transfer"),
                            ("resolved", "Resolved"),
                            ("info", "Info"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("lat", models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                (
                    "long",
                    models.DecimalField(decimal_places=6, max_digits=9, null=True),
                ),
                (
                    "geo_location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("description", models.TextField(null=True)),
                ("follow", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                ("did", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Information",
            fields=[
                ("inid", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "information_type",
                    models.CharField(
                        choices=[
                            ("drug", "Drug"),
                            ("extortion", "Extortion"),
                            ("Vehicle", "Vehicle"),
                        ],
                        default="drug",
                        max_length=15,
                    ),
                ),
                ("heading", models.TextField()),
                ("content", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Media",
            fields=[
                ("mid", models.BigAutoField(primary_key=True, serialize=False)),
                ("pid", models.BigIntegerField(default=0)),
                (
                    "mtype",
                    models.CharField(
                        choices=[
                            ("video", "Video"),
                            ("photo", "Photo"),
                            ("audio", "Audio"),
                            ("document", "Document"),
                        ],
                        default="Photo",
                        max_length=10,
                    ),
                ),
                (
                    "ptype",
                    models.CharField(
                        choices=[
                            ("case", "Case"),
                            ("history", "History"),
                            ("comment", "Comment"),
                        ],
                        default="case",
                        max_length=10,
                    ),
                ),
                ("path", models.FileField(upload_to=api.utl.get_upload_path)),
                ("description", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PoliceStation",
            fields=[
                ("pid", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("address", models.TextField(null=True)),
                (
                    "lat",
                    models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
                ),
                (
                    "long",
                    models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
                ),
                (
                    "distance",
                    models.DecimalField(decimal_places=2, max_digits=9, null=True),
                ),
                (
                    "geo_location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "did",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.district"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PoliceStationContact",
            fields=[
                ("ps_cid", models.BigAutoField(primary_key=True, serialize=False)),
                ("contactName", models.CharField(max_length=50, null=True)),
                ("number", models.CharField(max_length=15)),
                (
                    "pid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.policestation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PoliceOfficer",
            fields=[
                ("oid", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "rank",
                    models.CharField(
                        choices=[
                            ("1", "Constable"),
                            ("2", "Head Constable"),
                            ("3", "ASI"),
                            ("4", "SI"),
                            ("5", "Inspector"),
                            ("6", "DySP"),
                            ("7", "ASP"),
                            ("9", "SP"),
                            ("10", "SSP"),
                            ("11", "DIGP"),
                            ("12", "IGP"),
                            ("13", "ADG"),
                            ("14", "DGP"),
                        ],
                        default="Inspector",
                        max_length=10,
                    ),
                ),
                ("entryDate", models.DateField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("mobile", models.CharField(max_length=55, null=True)),
                (
                    "pid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.policestation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LostVehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("regNumber", models.CharField(max_length=30)),
                (
                    "chasisNumber",
                    models.CharField(default="N/A", max_length=50, null=True),
                ),
                (
                    "engineNumber",
                    models.CharField(default="N/A", max_length=50, null=True),
                ),
                ("make", models.CharField(default="N/A", max_length=50, null=True)),
                ("model", models.CharField(default="N/A", max_length=50, null=True)),
                (
                    "description",
                    models.CharField(default="N/A", max_length=500, null=True),
                ),
                (
                    "caseId",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="api.case"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Emergency",
            fields=[
                ("emid", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(default="N/A", max_length=50, null=True)),
                ("number", models.CharField(max_length=100, null=True)),
                ("lat", models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                (
                    "long",
                    models.DecimalField(decimal_places=6, max_digits=9, null=True),
                ),
                (
                    "did",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.district"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("cmtid", models.BigAutoField(primary_key=True, serialize=False)),
                ("content", models.TextField(null=True)),
                (
                    "cid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.case"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CaseHistory",
            fields=[
                ("chid", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "cstate",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("assign", "Assign"),
                            ("transfer", "Transfer"),
                            ("resolved", "Resolved"),
                            ("info", "Info"),
                        ],
                        max_length=15,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("description", models.TextField(null=True)),
                (
                    "cid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="api.case"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="case",
            name="oid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="api.policeofficer"
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="pid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="api.policestation"
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
