# Generated by Django 4.1 on 2023-03-09 11:15

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='cUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('user', 'User'), ('police', 'Police'), ('Admin', 'Admin')], default='user', max_length=10)),
                ('address', models.TextField(null=True)),
                ('pincode', models.CharField(max_length=10)),
                ('otp_code', models.CharField(blank=True, default=None, max_length=6, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('cid', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('drug', 'Drug'), ('vehicle', 'Vehicle'), ('extortion', 'Extortion')], default='Drug', max_length=10)),
                ('cstate', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('accepted', 'Accepted'), ('transferred', 'Transferred'), ('resolved', 'Resolved'), ('info', 'Info')], default='pending', max_length=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('Location', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('description', models.TextField(null=True)),
                ('follow', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CaseHistory',
            fields=[
                ('chid', models.BigAutoField(primary_key=True, serialize=False)),
                ('cstate', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('accepted', 'Accepted'), ('transferred', 'Transferred'), ('resolved', 'Resolved'), ('info', 'Info')], max_length=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(null=True)),
                ('cid', models.ForeignKey(db_column='case_cid', on_delete=django.db.models.deletion.DO_NOTHING, to='api.case')),
                ('user', models.ForeignKey(db_column='user_username', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('did', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PoliceStation',
            fields=[
                ('pid', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('address', models.TextField(null=True)),
                ('Location', models.DecimalField(decimal_places=6, max_digits=9)),
                ('did', models.ForeignKey(db_column='district_did', on_delete=django.db.models.deletion.CASCADE, to='api.district')),
            ],
        ),
        migrations.CreateModel(
            name='PoliceStationContact',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('contactName', models.CharField(max_length=50, null=True)),
                ('number', models.CharField(max_length=15)),
                ('pid', models.ForeignKey(db_column='police_station_pid', on_delete=django.db.models.deletion.CASCADE, to='api.policestation')),
            ],
        ),
        migrations.CreateModel(
            name='PoliceOfficer',
            fields=[
                ('oid', models.BigAutoField(primary_key=True, serialize=False)),
                ('rank', models.CharField(choices=[{'Designation': 'Constable', 'Rank:': 1}, {'Designation': 'Head Constable', 'Rank:': 2}, {'Designation': 'Assistant Sub-Inspector', 'Rank:': 3}, {'Designation': 'Sub-Inspector', 'Rank:': 4}, {'Designation': 'Inspector', 'Rank:': 5}, {'Designation': 'DySP', 'Rank:': 6}, {'Designation': 'ASP', 'Rank:': 7}, {'Designation': 'SP', 'Rank:': 9}, {'Designation': 'SSP', 'Rank:': 10}, {'Designation': 'DIGP', 'Rank:': 11}, {'Designation': 'IGP', 'Rank:': 12}, {'Designation': 'ADG', 'Rank:': 13}, {'Designation': 'DGP', 'Rank:': 14}], default=5, max_length=20)),
                ('entryDate', models.DateField(auto_now=True)),
                ('cstate', models.CharField(default='active', max_length=10)),
                ('mobile', models.CharField(max_length=55, null=True)),
                ('pid', models.ForeignKey(db_column='police_station_pid', on_delete=django.db.models.deletion.DO_NOTHING, to='api.policestation')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('mid', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('video', 'Video'), ('photo', 'Photo'), ('audio', 'Audio'), ('document', 'Document')], default='Photo', max_length=10)),
                ('path', models.CharField(max_length=50, null=True)),
                ('chid', models.ForeignKey(db_column='case_history_chid', on_delete=django.db.models.deletion.CASCADE, to='api.casehistory')),
            ],
        ),
        migrations.CreateModel(
            name='LostVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegNumber', models.CharField(max_length=30)),
                ('chaseNumber', models.CharField(max_length=50, null=True)),
                ('engineNumber', models.CharField(max_length=50, null=True)),
                ('make', models.CharField(max_length=50, null=True)),
                ('model', models.CharField(max_length=50, null=True)),
                ('caseId', models.OneToOneField(db_column='Case_cid', on_delete=django.db.models.deletion.DO_NOTHING, to='api.case')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='oid',
            field=models.ForeignKey(db_column='police_officer_oid', on_delete=django.db.models.deletion.DO_NOTHING, to='api.policeofficer'),
        ),
        migrations.AddField(
            model_name='case',
            name='pid',
            field=models.ForeignKey(db_column='police_station_pid', on_delete=django.db.models.deletion.DO_NOTHING, to='api.policestation'),
        ),
        migrations.AddField(
            model_name='case',
            name='user',
            field=models.ForeignKey(db_column='user_username', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
