# Generated by Django 4.1 on 2023-03-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='Location',
            new_name='lat',
        ),
        migrations.RemoveField(
            model_name='policestation',
            name='Location',
        ),
        migrations.AddField(
            model_name='case',
            name='long',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='policestation',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='policestation',
            name='long',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='policestationcontact',
            name='cid',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
