# Generated by Django 4.2.3 on 2023-07-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cuser",
            name="otp_code",
        ),
        migrations.RemoveField(
            model_name="cuser",
            name="pincode",
        ),
        migrations.AddField(
            model_name="cuser",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
