# Generated by Django 4.1 on 2023-03-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_location_case_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('police', 'Police'), ('admin', 'Admin')], default='user', max_length=10),
        ),
        migrations.AlterField(
            model_name='policestation',
            name='lat',
            field=models.DecimalField(decimal_places=9, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='policestation',
            name='long',
            field=models.DecimalField(decimal_places=9, default=0.0, max_digits=9),
        ),
    ]
