# Generated by Django 4.2.3 on 2023-07-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_remove_cuser_otp_code_remove_cuser_pincode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cuser",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
