# Generated by Django 4.2.3 on 2023-07-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_cuser_is_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="cuser",
            name="aadhar_card_no",
            field=models.CharField(blank=True, max_length=56),
        ),
    ]
