# Generated by Django 4.1 on 2023-03-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_policestation_lat_alter_policestation_long'),
    ]

    operations = [
        migrations.AddField(
            model_name='policestation',
            name='d1',
            field=models.FloatField(null=True),
        ),
    ]
