# Generated by Django 4.1 on 2023-03-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_policestation_d1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policestation',
            name='d1',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
    ]
