# Generated by Django 4.1 on 2023-03-13 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_policestation_d1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policestation',
            old_name='d1',
            new_name='distance',
        ),
    ]
