# Generated by Django 4.2.3 on 2023-07-22 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='casehistory',
            name='media',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.media'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='privacy',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='termscondition',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
