# Generated by Django 4.2.3 on 2023-07-23 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_casehistory_media_alter_contact_id_alter_privacy_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('case', 'user')},
        ),
    ]
