# Generated by Django 4.1 on 2023-03-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_cid_policestationcontact_ps_cid'),
    ]

    operations = [
        migrations.AddField(
            model_name='policeofficer',
            name='name',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
