# Generated by Django 4.2.3 on 2023-07-23 06:43

import api.utl
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_like_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('bid', models.BigAutoField(primary_key=True, serialize=False)),
                ('mtype', models.CharField(choices=[('video', 'Video'), ('photo', 'Photo'), ('audio', 'Audio'), ('document', 'Document')], default='Photo', max_length=10)),
                ('path', models.FileField(upload_to=api.utl.get_upload_path)),
                ('description', models.TextField(null=True)),
            ],
        ),
    ]
