# Generated by Django 4.2.3 on 2023-07-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
