# Generated by Django 4.1 on 2023-03-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_policeofficer_cstate_alter_policeofficer_rank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policeofficer',
            old_name='cstate',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='policeofficer',
            name='rank',
            field=models.CharField(choices=[('1', 'Constable'), (2, 'Head Constable'), (3, 'ASI'), (4, 'SI'), (5, 'Inspector'), (6, 'DySP'), (7, 'ASP'), (9, 'SP'), (10, 'SSP'), (11, 'DIGP'), (12, 'IGP'), (13, 'ADG'), (14, 'DGP')], default='Inspector', max_length=10),
        ),
    ]
