# Generated by Django 4.2.3 on 2023-07-25 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_case_distance"),
    ]

    operations = [
        migrations.RenameField(
            model_name="casehistory",
            old_name="cid",
            new_name="case",
        ),
        migrations.RemoveField(
            model_name="casehistory",
            name="chid",
        ),
        migrations.RemoveField(
            model_name="casehistory",
            name="media",
        ),
        migrations.RemoveField(
            model_name="media",
            name="mid",
        ),
        migrations.RemoveField(
            model_name="media",
            name="pid",
        ),
        migrations.RemoveField(
            model_name="media",
            name="ptype",
        ),
        migrations.AddField(
            model_name="case",
            name="medias",
            field=models.ManyToManyField(related_name="cases", to="api.media"),
        ),
        migrations.AddField(
            model_name="casehistory",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                # default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="casehistory",
            name="medias",
            field=models.ManyToManyField(related_name="case_histories", to="api.media"),
        ),
        migrations.AddField(
            model_name="media",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                # default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="case",
            name="oid",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.policeofficer",
            ),
        ),
    ]
