# Generated by Django 4.1 on 2023-03-14 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_policeofficer_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='title',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='type',
            field=models.CharField(choices=[('drug', 'Drug'), ('vehicle', 'Vehicle'), ('extortion', 'Extortion')], default='drug', max_length=10),
        ),
        migrations.AlterField(
            model_name='case',
            name='user',
            field=models.ForeignKey(db_column='cuser_username', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('cmtid', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(null=True)),
                ('chid', models.ForeignKey(db_column='case_history_chid', on_delete=django.db.models.deletion.CASCADE, to='api.casehistory')),
                ('user', models.ForeignKey(db_column='cuser_username', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='CommentMedia',
            fields=[
                ('cmmid', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('video', 'Video'), ('photo', 'Photo'), ('audio', 'Audio'), ('document', 'Document')], default='Photo', max_length=10)),
                ('path', models.CharField(max_length=50, null=True)),
                ('chid', models.ForeignKey(db_column='comment_cmtid', on_delete=django.db.models.deletion.CASCADE, to='api.comments')),
            ],
        ),
    ]
