# Generated by Django 4.2.3 on 2023-07-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_rename_cid_casehistory_case_remove_casehistory_chid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="medias",
            field=models.ManyToManyField(
                blank=True, related_name="cases", to="api.media"
            ),
        ),
    ]
