# Generated by Django 4.1 on 2023-03-15 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_case_title_alter_case_type_alter_case_user_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policeofficer',
            name='name',
        ),
        migrations.AddField(
            model_name='policeofficer',
            name='user',
            field=models.ForeignKey(db_column='cuser_username', default=7005698992, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, to_field='username'),
            preserve_default=False,
        ),
    ]
