# Generated by Django 4.2.3 on 2023-08-05 06:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_alter_case_medias"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="updated",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
