# Generated by Django 4.1.1 on 2023-03-18 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_policeofficer_name_policeofficer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
