# Generated by Django 4.2.3 on 2023-08-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0016_alter_case_cstate_alter_casehistory_cstate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="cstate",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("assign", "Assign"),
                    ("inprogress", "Inprogress"),
                    ("transfer", "Transfer"),
                    ("resolved", "Resolved"),
                    ("info", "Info"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="casehistory",
            name="cstate",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("assign", "Assign"),
                    ("inprogress", "Inprogress"),
                    ("transfer", "Transfer"),
                    ("resolved", "Resolved"),
                    ("info", "Info"),
                    ("rejected", "Rejected"),
                ],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="lostvehicle",
            name="regNumber",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
