# Generated by Django 4.1.1 on 2023-03-18 18:55

import api.utl
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_media_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='path',
            field=models.FileField(default=None, upload_to=api.utl.get_upload_path),
            preserve_default=False,
        ),
    ]
