# Generated by Django 4.2.3 on 2023-08-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0017_alter_case_cstate_alter_casehistory_cstate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="medias",
            field=models.ManyToManyField(related_name="comments", to="api.media"),
        ),
    ]
