# Generated by Django 4.1.1 on 2023-03-18 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_media_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='type',
            new_name='mtype',
        ),
        migrations.AddField(
            model_name='media',
            name='ptype',
            field=models.CharField(choices=[('case', 'Case'), ('history', 'History'), ('comment', 'Comment')], default='case', max_length=10),
        ),
        migrations.AlterField(
            model_name='media',
            name='chid',
            field=models.BigIntegerField(default=-1),
        ),
    ]
