# Generated by Django 4.2.3 on 2023-08-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0018_comment_medias"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="medias",
            field=models.ManyToManyField(
                blank=True, related_name="comments", to="api.media"
            ),
        ),
    ]
