# Generated by Django 4.1.1 on 2023-03-18 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_rename_type_media_mtype_media_ptype_alter_media_chid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='chid',
            new_name='pid',
        ),
    ]
