# Generated by Django 4.2.3 on 2023-08-17 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0019_alter_comment_medias"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="oid",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.policeofficer",
            ),
        ),
    ]
