# Generated by Django 4.1.1 on 2023-03-18 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_rename_chid_media_pid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lostvehicle',
            old_name='chaseNumber',
            new_name='chasisNumber',
        ),
        migrations.RenameField(
            model_name='lostvehicle',
            old_name='RegNumber',
            new_name='regNumber',
        ),
        migrations.AlterField(
            model_name='media',
            name='pid',
            field=models.BigIntegerField(default=0),
        ),
    ]
