# Generated by Django 4.1.1 on 2023-03-18 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_rename_chasenumber_lostvehicle_chasisnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostvehicle',
            name='chasisNumber',
            field=models.CharField(default='N/A', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lostvehicle',
            name='engineNumber',
            field=models.CharField(default='N/A', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lostvehicle',
            name='make',
            field=models.CharField(default='N/A', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lostvehicle',
            name='model',
            field=models.CharField(default='N/A', max_length=50, null=True),
        ),
    ]
