# Generated by Django 4.2.3 on 2023-08-23 15:21

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0020_alter_case_oid"),
    ]

    operations = [
        migrations.AddField(
            model_name="emergency",
            name="geo_location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326
            ),
        ),
    ]
