# Generated by Django 4.2.3 on 2023-08-31 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0021_emergency_geo_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="lostvehicle",
            name="color",
            field=models.CharField(blank=True, default="", max_length=56),
        ),
    ]
