# Generated by Django 4.1.1 on 2023-03-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_lostvehicle_regnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostvehicle',
            name='regNumber',
            field=models.CharField(max_length=30),
        ),
    ]
