# Generated by Django 4.2.3 on 2023-09-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0023_policeofficer_report_on_this"),
    ]

    operations = [
        migrations.AddField(
            model_name="casehistory",
            name="lat",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="casehistory",
            name="long",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="case",
            name="cstate",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("assign", "Assign"),
                    ("visited", "Visited"),
                    ("inprogress", "Inprogress"),
                    ("transfer", "Transfer"),
                    ("resolved", "Resolved"),
                    ("info", "Info"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="casehistory",
            name="cstate",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("assign", "Assign"),
                    ("visited", "Visited"),
                    ("inprogress", "Inprogress"),
                    ("transfer", "Transfer"),
                    ("resolved", "Resolved"),
                    ("info", "Info"),
                    ("rejected", "Rejected"),
                ],
                max_length=15,
            ),
        ),
    ]
