# Generated by Django 4.1.1 on 2023-03-19 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_lostvehicle_regnumber'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.DeleteModel(
            name='CommentMedia',
        ),
    ]
