# Generated by Django 4.2.3 on 2023-09-10 16:45

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0024_casehistory_lat_casehistory_long_alter_case_cstate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="casehistory",
            name="geo_location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326
            ),
        ),
    ]
