# Generated by Django 4.1.1 on 2023-03-19 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_rename_comments_comment_delete_commentmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='chid',
            field=models.ForeignKey(db_column='case_cid', on_delete=django.db.models.deletion.CASCADE, to='api.case'),
        ),
    ]
