# Generated by Django 4.1.1 on 2023-03-19 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_comment_chid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='chid',
            new_name='cid',
        ),
    ]
