# Generated by Django 4.2.3 on 2023-11-17 05:11

import api.models
import api.utl
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0025_casehistory_geo_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="path",
            field=models.FileField(
                upload_to=api.utl.get_upload_path,
                validators=[api.models.file_type_validator],
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="path",
            field=models.FileField(
                upload_to=api.utl.get_upload_path,
                validators=[api.models.file_type_validator],
            ),
        ),
    ]
