# Generated by Django 4.2.3 on 2023-11-17 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_banner_path_alter_media_path'),
        ('api', '0026_loggedinuser'),
    ]

    operations = [
    ]
