# Generated by Django 4.2.3 on 2023-07-10 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_rename_chid_comment_cid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('inid', models.BigAutoField(primary_key=True, serialize=False)),
                ('information_type', models.CharField(choices=[('drug', 'Drug'), ('extortion', 'Extortion'), ('Vehicle', 'Vehicle')], default='drug', max_length=15)),
                ('heading', models.TextField()),
                ('content', models.TextField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='case',
            name='cstate',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('accepted', 'Accepted'), ('assign', 'Assign'), ('transfer', 'Transfer'), ('resolved', 'Resolved'), ('info', 'Info')], default='pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='casehistory',
            name='cstate',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('accepted', 'Accepted'), ('assign', 'Assign'), ('transfer', 'Transfer'), ('resolved', 'Resolved'), ('info', 'Info')], max_length=15),
        ),
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('emid', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='N/A', max_length=50, null=True)),
                ('number', models.CharField(max_length=100, null=True)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('long', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('did', models.ForeignKey(db_column='district_did', on_delete=django.db.models.deletion.CASCADE, to='api.district')),
            ],
        ),
    ]
