# Generated by Django 4.2.3 on 2023-11-18 07:35

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_merge_20231117_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuser',
            name='mobile',
            field=models.CharField(max_length=26, unique=True, validators=[api.models.mobile_validator]),
        ),
    ]
