# Generated by Django 4.2.3 on 2023-07-15 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_information_alter_case_cstate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostvehicle',
            name='description',
            field=models.CharField(default='N/A', max_length=500, null=True),
        ),
    ]
