# Generated by Django 4.2.3 on 2023-11-25 06:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0028_alter_cuser_mobile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="cstate",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("found", "Found"),
                    ("assign", "Assign"),
                    ("visited", "Visited"),
                    ("inprogress", "Inprogress"),
                    ("transfer", "Transfer"),
                    ("resolved", "Resolved"),
                    ("info", "Info"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="casehistory",
            name="cstate",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("found", "Found"),
                    ("assign", "Assign"),
                    ("visited", "Visited"),
                    ("inprogress", "Inprogress"),
                    ("transfer", "Transfer"),
                    ("resolved", "Resolved"),
                    ("info", "Info"),
                    ("rejected", "Rejected"),
                ],
                max_length=15,
            ),
        ),
    ]
