# Generated by Django 4.2.3 on 2023-11-26 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0029_alter_case_cstate_alter_casehistory_cstate"),
    ]

    operations = [
        migrations.CreateModel(
            name="PoliceStationSupervisor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "officer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policestation_supervisor",
                        to="api.policeofficer",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policestation_supervisor",
                        to="api.policestation",
                    ),
                ),
            ],
            options={
                "unique_together": {("officer", "station")},
            },
        ),
    ]
