# Generated by Django 4.2.3 on 2023-07-16 15:00

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_cuser_mobile_alter_cuser_pincode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='geo_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='policestation',
            name='geo_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='case',
            name='cstate',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('assign', 'Assign'), ('transfer', 'Transfer'), ('resolved', 'Resolved'), ('info', 'Info')], default='pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='casehistory',
            name='cstate',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('assign', 'Assign'), ('transfer', 'Transfer'), ('resolved', 'Resolved'), ('info', 'Info')], max_length=15),
        ),
    ]
