# Generated by Django 4.2.3 on 2023-11-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0030_policestationsupervisor"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="drug_issue_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("drug_peddling", "Drug Peddling"),
                    ("drug_consumption", "Drug Consumption"),
                    ("drug_cultivation", "Drug Cultivation"),
                    ("needs_counselling", "Needs Counselling"),
                    ("needs_rehabilitation", "Needs Rehabilitation"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
