# Generated by Django 4.2.3 on 2023-07-18 16:30

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_case_geo_location_policestation_geo_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('offender', 'Habitual offender'), ('wanted', 'Wanted'), ('proclaimed', 'Proclaimed Offender')], default='offender', max_length=25)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
        migrations.CreateModel(
            name='Victim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('missing_children', 'Missing Children'), ('children_found', 'Children Found'), ('missing_person', 'Missing Person'), ('dead_body', 'Dead Bodied Found'), ('other', 'Any other case ')], default='missing_children', max_length=25)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
    ]
