# Generated by Django 4.2.3 on 2023-11-27 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_case_drug_issue_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyType',
            fields=[
                ('emtid', models.BigAutoField(primary_key=True, serialize=False)),
                ('service_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='emergency',
            name='did',
        ),
        migrations.AddField(
            model_name='emergency',
            name='tid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.emergencytype'),
        ),
    ]
