# Generated by Django 4.2.3 on 2023-11-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_emergencytype_remove_emergency_did_emergency_tid'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostvehicle',
            name='type',
            field=models.CharField(choices=[('stolen', 'Stolen'), ('Abandoned', 'Abandoned')], default='stolen', max_length=10),
        ),
    ]
