# Generated by Django 4.2.3 on 2023-11-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_lostvehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostvehicle',
            name='type',
            field=models.CharField(choices=[('stolen', 'Stolen'), ('abandoned', 'Abandoned')], default='stolen', max_length=10),
        ),
    ]
