# Generated by Django 4.2.3 on 2024-01-13 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_lostvehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='mtype',
            field=models.CharField(choices=[('video', 'Video'), ('photo', 'Photo'), ('audio', 'Audio'), ('document', 'Document')], default='photo', max_length=10),
        ),
        migrations.CreateModel(
            name='UserOTPBaseKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_32_secret_key', models.CharField(blank=True, max_length=16, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_otp', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
