# Generated by Django 4.2.3 on 2024-01-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_media_mtype_userotpbasekey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotpbasekey',
            name='base_32_secret_key',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
