# Generated by Django 4.2.3 on 2024-01-24 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_userotpbasekey_base_32_secret_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='userotpbasekey',
            name='last_otp_generation_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userotpbasekey',
            name='otp_generation_count',
            field=models.IntegerField(default=0),
        ),
    ]
