# Generated by Django 4.2.3 on 2024-01-29 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_userotpbasekey_last_otp_generation_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policestation',
            name='distance',
        ),
        migrations.AlterField(
            model_name='cuser',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
