# Generated by Django 4.2.3 on 2024-01-29 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_remove_policestation_distance_alter_cuser_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergency',
            name='geo_location',
        ),
    ]
