# Generated by Django 4.2.3 on 2024-01-29 05:23

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_remove_emergency_geo_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergency',
            name='geo_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
